spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: f750831ea8fd94238ded
            client-secret: 70b51033c5894fbdccc6cab1ee4c46c726aaa0b1

#logging:
#  level:
#    org.springframework.security: DEBUG
